### ISSUE TITLE
NEED FIX (ASAP): Category update is not saving updates for the fields

### ISSUE THREAD

**Issue by rickzx98** [great-design-and-systems/category-service#7]

**Comment by analynf** [comment]
Please use /update-field/:fieldId when updating fields

**Comment by rickzx98** [comment]
Fields have to be updated the same time category is updated like fields are created when you create a category.

**Comment by rickzx98** [comment]
This is the request payload when updating


`{"name":"Books","fields":[{"_id":"5877a61d7251700ce0ba37fd","name":"isbn","fieldType":"text","categoryId":"5877a61d7251700ce0ba37fc","__v":0,"createdOn":"2017-01-12T15:51:57.631Z","isRequired":true,"isFilter":true},{"_id":"5877a61d7251700ce0ba37fe","name":"author","fieldType":"text","categoryId":"5877a61d7251700ce0ba37fc","__v":0,"createdOn":"2017-01-12T15:51:57.632Z","isRequired":true,"isFilter":true}],"rules":["needsCredentials","GridLayout","listLayout","tableLayout","needsID","needsApproval"]}`

**Comment by rickzx98** [comment]
The same apply with rules"

**Comment by rickzx98** [comment]
Any update on this?

**Comment by analynf** [comment]
Fixed.

**Comment by analynf** [comment]
Please make sure to use the following request format:
```json
{  
    "category" : { 
        "name" : "Category Name",
        "iconGlyph" : "value",
        "iconField" : "value",
        "rules" : ["needsCredentials","GridLayout","listLayout","tableLayout","needsID","needsApproval"],
        "approver" : "value"
    },  
    "fields" : [  
        { "_id" : "fieldId1", "name" : "fieldName1", "fieldType" : "Number", "isFilter" : true, "isRequired" : false },
        { "_id" : "fieldId2", "name" : "fieldName2", "fieldType" : "Text", "isFilter" : false, "isRequired" : true }, 
        { "_id" : "fieldId3", "name" : "fieldName3", "fieldType" : "Date", "isFilter" : true, "isRequired" : false }
    ] 
} 
```
